; Kunena Forum treek translation
;
COM_KUNENA_RE_TREEK="Ответ на:"
COM_KUNENA_TREEK_GOTO_PARENT="Перейти к родительскому посту"
COM_KUNENA_REPLYTO_HEADER_TREEK="Ответ на %1$s'а пост: %2$s"
COM_KUNENA_TREEK_ARROW_UP="⇑"
COM_KUNENA_TREEK_ARROW_RIGHT="⇒"
COM_KUNENA_TREEK_ARROW_CANCEL_ONE="⇍"
COM_KUNENA_TREEK_ARROW_SUFFIX_OFF="⇒"
COM_KUNENA_TREEK_SUFFIX_OFF_TOOLTIP="Суффиксы отключены. Нажмите для включения"
COM_KUNENA_TREEK_ARROW_CANCEL="⇏"
COM_KUNENA_TREEK_CANCEL_SUFFIX_TOOLTIP="Удалить суффикс в ответе"
COM_KUNENA_TREEK_CANCEL_ONE_TOOLTIP="Отключить суффиксы во всех ответах"
; Переопределеня
COM_KUNENA_GEN_SUBJECT = "Заголовок"
COM_KUNENA_BY = "Автор: "
COM_KUNENA_RSS_BY = ""
