; Kunena Forum treek Übersetzung
;
COM_KUNENA_RE_TREEK="Antwort auf:"
COM_KUNENA_TREEK_GOTO_PARENT="Zum uebergeordneten Beitrag gehen"
COM_KUNENA_REPLYTO_HEADER_TREEK="Antwort auf den Beitrag von %1$s: %2$s"
COM_KUNENA_TREEK_ARROW_UP="⇑"
COM_KUNENA_TREEK_ARROW_RIGHT="⇒"
COM_KUNENA_TREEK_ARROW_CANCEL_ONE="⇍"
COM_KUNENA_TREEK_ARROW_SUFFIX_OFF="⇒"
COM_KUNENA_TREEK_SUFFIX_OFF_TOOLTIP="Suffixe sind deaktiviert. Zum Aktivieren klicken"
COM_KUNENA_TREEK_ARROW_CANCEL="⇏"
COM_KUNENA_TREEK_CANCEL_SUFFIX_TOOLTIP="Suffix in der Antwort entfernen"
COM_KUNENA_TREEK_CANCEL_ONE_TOOLTIP="Suffixe in allen Antworten deaktivieren"
; Neudefinitionen von Konstanten
COM_KUNENA_GEN_SUBJECT = "Titel"
